"""Make driving_license_number and aadhar_number optional on Rider

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="driving_license_number",
            field=models.CharField(max_length=50, unique=True, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="rider",
            name="aadhar_number",
            field=models.CharField(max_length=12, unique=True, null=True, blank=True),
        ),
    ]
