# Generated by Django 5.0.8 on 2026-06-07 14:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('from_address', models.CharField(max_length=500)),
                ('from_latitude', models.FloatField()),
                ('from_longitude', models.FloatField()),
                ('to_address', models.CharField(max_length=500)),
                ('to_latitude', models.FloatField()),
                ('to_longitude', models.FloatField()),
                ('items_description', models.TextField()),
                ('distance_in_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_time_minutes', models.IntegerField(default=30)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('total_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Waiting for rider'), ('accepted', 'Accepted - Rider accepted'), ('picked_up', 'Picked Up - Item collected'), ('in_transit', 'In Transit - On the way'), ('reached', 'Reached - At destination'), ('completed', 'Completed - Order delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent_to', models.JSONField(default=list, help_text='List of rider IDs notified')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_notified', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_notifications',
                'ordering': ['-notified_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_status_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
