# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FareConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rate_per_km", models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ("minimum_fare", models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fare_configs",
                "ordering": ["-updated_at"],
            },
        ),
    ]
