// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClDkbUmF21rKeoAPMx9Zrpep9e9yyqz10',
    appId: '1:28332338228:web:6bc42c593be1bf829cee61',
    messagingSenderId: '28332338228',
    projectId: 'dodoo-admin-refresh',
    authDomain: 'dodoo-admin-refresh.firebaseapp.com',
    storageBucket: 'dodoo-admin-refresh.firebasestorage.app',
    measurementId: 'G-WWCXTWNJK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_i3DEJrpHYr9xtyv4jV15esHQNbpQz0',
    appId: '1:28332338228:android:88fb24b997b69c7d9cee61',
    messagingSenderId: '28332338228',
    projectId: 'dodoo-admin-refresh',
    storageBucket: 'dodoo-admin-refresh.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhak6Wf9TYqthaiCTj7L_ToqAo_0LBtEI',
    appId: '1:28332338228:ios:da9449dcc91eedf29cee61',
    messagingSenderId: '28332338228',
    projectId: 'dodoo-admin-refresh',
    storageBucket: 'dodoo-admin-refresh.firebasestorage.app',
    iosBundleId: 'com.example.dodooDeliveryApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhak6Wf9TYqthaiCTj7L_ToqAo_0LBtEI',
    appId: '1:28332338228:ios:da9449dcc91eedf29cee61',
    messagingSenderId: '28332338228',
    projectId: 'dodoo-admin-refresh',
    storageBucket: 'dodoo-admin-refresh.firebasestorage.app',
    iosBundleId: 'com.example.dodooDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClDkbUmF21rKeoAPMx9Zrpep9e9yyqz10',
    appId: '1:28332338228:web:66ce46f700edf5c29cee61',
    messagingSenderId: '28332338228',
    projectId: 'dodoo-admin-refresh',
    authDomain: 'dodoo-admin-refresh.firebaseapp.com',
    storageBucket: 'dodoo-admin-refresh.firebasestorage.app',
    measurementId: 'G-9R2RR88HJC',
  );
}
